from typing import List

from pydantic import BaseModel, ConfigDict, Field


class UserProfile(BaseModel):
    """Consolidated user information extracted from the conversation.

    This model represents durable user-level signals inferred from messages,
    such as preferences and hard constraints, and is intended for downstream
    personalization and filtering logic.
    """

    prefs: List[str] = Field(
        default_factory=list,
        description=(
            "User preferences (e.g., 'Likes Python', "
            "'Prefers concise answers')."
        ),
    )
    constraints: List[str] = Field(
        default_factory=list,
        description=(
            "Hard constraints that must not be violated "
            "(e.g., 'No Java', 'Speak English only')."
        ),
    )


class MessageRange(BaseModel):
    """Defines the inclusive range of messages covered by a summary.

    This metadata is computed by the application layer and should not be
    generated by the LLM.
    """

    model_config = ConfigDict(populate_by_name=True)

    start_index: int = Field(
        ...,
        alias="from",
        description="The starting message index (inclusive).",
    )
    end_index: int = Field(
        ...,
        alias="to",
        description="The ending message index (inclusive).",
    )


class SessionSummaryContent(BaseModel):
    """Content-only schema for AI generation.

    This model intentionally excludes message indices to prevent the LLM from
    hallucinating or inferring positional metadata.
    """

    user_profile: UserProfile
    key_facts: List[str] = Field(
        default_factory=list,
        description="Important facts established during the session.",
    )
    decisions: List[str] = Field(
        default_factory=list,
        description="Key decisions that were made or agreed upon.",
    )
    open_questions: List[str] = Field(
        default_factory=list,
        description="Unresolved questions or topics to revisit later.",
    )
    todos: List[str] = Field(
        default_factory=list,
        description="Action items or next steps identified in the session.",
    )


class SessionSummary(SessionSummaryContent):
    """Full session summary used by the application layer.

    This schema combines AI-generated summary content with deterministic,
    Python-calculated metadata.
    """

    message_range_summarized: MessageRange = Field(
        ...,
        description=(
            "The exact range of message indices covered by this summary."
        ),
    )